const TrackerUI=(()=>{
 const KEY='icewind-ythryn-tracker-v1',T=YthrynTracker;
 let state=T.fresh(),history=[],locked=false,storageWarning='',message='',exploring=true;
 const safe=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
 const time=n=>{const d=Math.floor(n/1440),h=Math.floor(n%1440/60),m=n%60;return (d?d+' d ':'')+h+' h '+String(m).padStart(2,'0')+' min';};
 const remaining=at=>at<=state.time?'Termin minął '+time(state.time-at)+' temu':'Za '+time(at-state.time);
 function load(){
  let raw;try{raw=localStorage.getItem(KEY);}catch{storageWarning='Przeglądarka blokuje zapis. Przed zamknięciem pobierz kopię stanu.';return;}
  if(!raw)return;
  try{const data=JSON.parse(raw);state=T.validate(data.state);history=Array.isArray(data.undo)?data.undo.slice(-20).map(T.validate):[];}
  catch{locked=true;storageWarning='Zapisany stan jest nieprawidłowy. Nie nadpisuję go. Wczytaj kopię lub świadomie rozpocznij nowy zapis.';}
 }
 function persist(){try{localStorage.setItem(KEY,JSON.stringify({state,undo:history.slice(-20)}));storageWarning='';}catch{storageWarning='Nie udało się zapisać zmian w przeglądarce. Stan działa w tej karcie — pobierz kopię przed zamknięciem.';}}
 function link(title,label=title){const p=DATA.pages.find(p=>p.title===title||p.title.startsWith(title+'.'));return p?`<a href="#${p.id}">${safe(label)}</a>`:safe(label);}
 function sectionLink(heading,label){for(const p of DATA.pages){const match=p.html.match(new RegExp('<h[1-6] id="([^"]+)">'+heading+'<'));if(match)return `<a href="#${p.id}~${match[1]}">${safe(label||heading)}</a>`;}return link(heading,label);}
 function button(action,text,attrs=''){return `<button type="button" data-track="${action}" ${attrs}>${text}</button>`;}
 function alarms(){
  const items=[];
  for(const p of state.players)if(p.hunger&&p.hungerNext===null)items.push(p.name+': ustal termin kolejnego posiłku lub rzutu na głód'+(p.exhaustion===null?' i obecny poziom wyczerpania':'')+'.');
  if(state.entry===null&&state.avarice==='waiting')items.push('Zegar Avarice wymaga czasu drogi od otwarcia lodowca do wejścia do Ythryn.');
  for(const p of state.players){const roll=T.due(state,p);if(roll)items.push(`${p.name}: ${roll.type==='exposure'?'ekspozycja na Arcane Blight, Kondycja ST 15':'zaraza po odpoczynku, Kondycja ST '+p.dc} (termin: ${time(roll.at)}).`);if(p.hunger&&p.hungerNext!==null&&p.hungerNext<=state.time)items.push(`${p.name}: kończy się ulga od głodu — jedzenie lub Kondycja ST 15.`);}
  if(T.encounters(state))items.push(`Godzinowe spotkania do rozliczenia: ${T.encounters(state)}.`);
  if(state.buildingChecks)items.push(`Przeszukania do rozliczenia (spotkanie i skarb): ${state.buildingChecks}.`);
  if(state.patrolChecks)items.push(`Sprawdzenia patrolu Avarice (20%): ${state.patrolChecks}.`);
  if(state.entry!==null&&state.avarice==='waiting'&&state.time+state.entry>=2160+state.avariceDelay)items.push('Nadszedł planowany termin przybycia Avarice. Potwierdź jej faktyczne przybycie w zegarach frakcji.');
  if(state.auril==='waiting'&&state.time>=1440)items.push('Minęła doba: termin przybycia Auril, jeśli nie została wcześniej pokonana.');
  for(const t of state.timers.filter(t=>!t.done&&t.at<=state.time))items.push(t.name+' — termin: '+time(t.at)+'.');
  return items;
 }
 function player(p){
  const roll=T.due(state,p),status={healthy:'Bez infekcji',infected:'Zarażony',immune:'Wyleczony · odporny',nothic:'Przemiana w nothika'}[p.status];
  const text=roll?(roll.type==='exposure'?'Do rzutu: ekspozycja, Kondycja ST 15':'Do rzutu: po odpoczynku, Kondycja ST '+p.dc):p.status==='healthy'?'Następna ekspozycja: '+time(p.nextExposure)+' · '+remaining(p.nextExposure):p.status==='infected'?'Następny rzut po długim odpoczynku':p.status==='immune'?'Dalsze ekspozycje nie wymagają rzutu':'Odwrócenie przemiany: wish lub boska interwencja';
  return `<section class="track-player ${roll?'due':''}"><header><h3>${p.name}</h3><span class="track-badge">${status}</span></header><div class="track-stats"><div><small>Aktualna ST (DC)</small><strong>${p.status==='immune'?'0':p.dc}</strong></div><div><small>Sukcesy po odpoczynku</small><strong>${p.success}</strong></div><div><small>Porażki po odpoczynku</small><strong>${p.fail}<small> / 3</small></strong></div></div><p class="track-caption">Ekspozycje: ${p.exposureSuccess} udanych / ${p.exposureFail} nieudanych. Zakażenie nie dodaje porażki do licznika 0–3.</p><p class="track-due">${text}</p><div class="track-actions">${roll?.type==='recovery'?`<label>Wynik k6 <select id="die-${p.id}" aria-label="Wynik k6 — ${p.name}"><option value="">—</option>${[1,2,3,4,5,6].map(n=>`<option>${n}</option>`).join('')}</select></label>`:''}${button('pass','Sukces',`data-player="${p.id}" ${roll?'':'disabled'}`)}${button('fail','Porażka',`data-player="${p.id}" ${roll?'':'disabled'}`)}${p.status==='infected'?button('heal','Wylecz magią',`data-player="${p.id}"`):''}</div><details class="track-edit"><summary>Korekta stanu</summary><form data-form="player" data-player="${p.id}" class="track-form"><label>Stan<select name="status">${[['healthy','Bez infekcji'],['infected','Zarażony'],['immune','Odporny'],['nothic','Nothik']].map(([v,l])=>`<option value="${v}" ${v===p.status?'selected':''}>${l}</option>`).join('')}</select></label><label>ST<input name="dc" type="number" min="0" max="100" value="${p.dc}" required></label><label>Sukcesy<input name="success" type="number" min="0" value="${p.success}" required></label><label>Porażki<input name="fail" type="number" min="0" max="3" value="${p.fail}" required></label><p class="track-caption">Korekta zamyka wcześniejsze oczekujące rzuty. Dla zdrowego nowa ekspozycja za 12 h; dla zarażonego następny odpoczynek. Wyniki ekspozycji pozostają w historii.</p><button>Zapisz korektę</button></form></details></section>`;
 }
 function render(){
  const host=document.querySelector('#tracker-panel');if(!host)return;
  const oldExplore=host.querySelector('#track-explore');if(oldExplore)exploring=oldExplore.checked;
  const alerts=alarms();
  const aTime=state.entry===null?'Wpisz czas od otwarcia lodowca do wejścia do miasta.':remaining(2160+state.avariceDelay-state.entry);
  host.innerHTML=`<div class="track-head"><div><span class="chapter-label">ROZDZIAŁ 07 / NARZĘDZIA MG</span><h1>Przetrwać w Ythryn</h1></div><div class="track-actions">${button('undo','↶ Cofnij',history.length?'':'disabled')}${button('export','Pobierz zapis')}${button('import','Wczytaj zapis')}<input id="tracker-import" type="file" accept="application/json,.json" hidden></div></div><p id="tracker-feedback" role="status" class="track-caption">${safe(message||'Zapis lokalny w tej przeglądarce. Kopia pliku HTML nie przenosi stanu — użyj „Pobierz zapis”.')}</p>${storageWarning?`<p class="track-warning">${safe(storageWarning)}</p>`:''}<fieldset class="track-fieldset" ${locked?'disabled':''}>
  <section class="track-card"><div class="track-clock"><div><span class="chapter-label">CZAS OD WEJŚCIA DO MIASTA</span><strong>${time(state.time)}</strong><small>Eksploracja: ${time(state.exploration)} · kolejne sprawdzenie spotkania za ${60-state.exploration%60} min eksploracji</small></div><div class="track-actions">${[5,30,60].map(n=>button('advance','+'+(n===60?'1 h':n+' min'),`data-minutes="${n}"`)).join('')}</div></div><form data-form="advance" class="track-form"><label>Dodaj minuty<input type="number" name="minutes" min="1" max="10080" value="10" required></label><label class="track-check"><input id="track-explore" type="checkbox" checked> To czas eksploracji</label><button>Dodaj czas</button></form><div class="track-actions">${button('building','Przeszukaj budynek · +30 min')}${button('new-building','Nowy budynek · bez zmiany czasu')}${button('rest','Długi odpoczynek drużyny · +8 h')}</div><details><summary>Odpoczynek o innej długości</summary><p class="track-caption">Dodaj odpowiednią liczbę minut bez zaznaczenia eksploracji, a następnie oznacz koniec odpoczynku całej drużyny. Przycisk poniżej nie dodaje czasu.</p>${button('rest-end','Zakończ odpoczynek · bez zmiany czasu')}</details></section>
  <section class="track-card"><h2>Do rozstrzygnięcia <span class="track-badge">${alerts.length}</span></h2>${alerts.length?'<ul class="track-alerts">'+alerts.map(a=>'<li>'+safe(a)+'</li>').join('')+'</ul>':'<p class="track-caption">Brak zaległych sprawdzeń. Czas zmienia się tylko po Twoim kliknięciu.</p>'}<div class="track-actions">${button('encounter','Rozlicz 1 spotkanie godzinowe',T.encounters(state)?'':'disabled')}${button('building-check','Rozlicz 1 przeszukanie',state.buildingChecks?'':'disabled')}${button('patrol','Rozlicz 1 patrol (20%)',state.patrolChecks?'':'disabled')}${link('Tabela spotkań','Tabela k100')}${sectionLink('Skarby Ythryn','Skarby')}</div><p class="track-caption">Przeszukanie dodaje osobne spotkanie i skarb. Jeśli przekroczysz pełną godzinę eksploracji, należne jest także sprawdzenie godzinowe. Oznaczaj tę samą wizytę jednym przyciskiem „Przeszukaj” albo „Nowy budynek”, aby nie dublować patrolu.</p></section>
  <section class="track-card"><h2>Arcane Blight — tajemna zaraza</h2><p class="track-caption">Ekspozycja: Kondycja ST 15 po 12 h. Kolejne ekspozycje zdrowych co 12 h to <strong>propozycja MG z notatek</strong>. Zarażeni rzucają po długim odpoczynku: sukces obniża ST o wpisany wynik k6; ST 0 daje wyleczenie i odporność. Trzecia porażka po odpoczynku oznacza przemianę. ${sectionLink('Tajemna zaraza','Pełne zasady')}</p><div class="track-players">${state.players.map(player).join('')}</div></section>
  <section class="track-card"><h2>Klątwa głodu — Tillo i Hugo</h2><p class="track-caption">Kronika z 28.09: obaj nadal mają klątwę. Nie zapisano godziny ostatniego posiłku ani wyczerpania — uzupełnij je przed kolejnym rzutem. Garść jedzenia daje godzinę ulgi. Kondycja ST 15: sukces kończy klątwę, porażka dodaje 1 wyczerpania. ${link('H12','Zasady H12')}</p><div class="track-players">${state.players.filter(p=>['Tillo','Hugo'].includes(p.name)).map(p=>`<div class="track-player"><h3>${p.name} · ${p.hunger?'klątwa aktywna':'klątwa zakończona'}</h3><p>${p.hunger?p.hungerNext===null?'Termin nieustalony':remaining(p.hungerNext):'Wyczerpanie pozostaje — rozliczaj je osobno.'}</p><form data-form="exhaustion" data-player="${p.id}" class="track-form"><label>Wyczerpanie<input name="value" type="number" min="0" max="6" value="${p.exhaustion??''}" placeholder="?" required></label><button>Zapisz</button></form><div class="track-actions">${button('feed','Jedzenie teraz · 1 h ulgi',`data-player="${p.id}" ${p.hunger?'':'disabled'}`)}${button('hunger-check','Rzut należny teraz',`data-player="${p.id}" ${p.hunger?'':'disabled'}`)}${button('hunger-pass','Sukces / zdjęcie klątwy',`data-player="${p.id}" ${p.hunger?'':'disabled'}`)}${button('hunger-fail','Porażka · +1 wyczerpania',`data-player="${p.id}" ${p.hunger&&p.hungerNext!==null&&p.hungerNext<=state.time?'':'disabled'}`)}</div></div>`).join('')}</div></section>
  <details class="track-card" open><summary>Zegary Avarice i Auril</summary><p><strong>Avarice:</strong> ${state.avarice==='waiting'?safe(aTime):state.avarice==='arrived'?'obecna — 20% szans na patrol przy nowym budynku':'wyłączona'}<br><strong>Auril:</strong> ${state.auril==='waiting'?remaining(1440):state.auril==='arrived'?'obecna':'wyłączona / pokonana'}</p><form data-form="factions" class="track-form"><label>Godziny od otwarcia lodowca do wejścia do Ythryn<input type="number" name="entry" min="0" max="100000" step="any" placeholder="Nieustalone" value="${state.entry===null?'':state.entry/60}"></label><label>Opóźnienie Avarice (godziny)<input type="number" name="delay" min="0" max="100000" step="any" value="${state.avariceDelay/60}" required></label>${['avarice','auril'].map(k=>`<label>${k==='avarice'?'Avarice':'Auril'}<select name="${k}">${[['waiting','Oczekiwana'],['arrived','Przybyła'],['disabled','Wyłączona / pokonana']].map(([v,l])=>`<option value="${v}" ${state[k]===v?'selected':''}>${l}</option>`).join('')}</select></label>`).join('')}<button>Zapisz zegary</button></form><p class="track-caption">Avarice: 36 h od otwarcia lodowca + opóźnienia. Auril: doba pobytu, jeśli nie została pokonana. Przekroczenie terminu wyświetla przypomnienie; faktyczne przybycie potwierdzasz powyżej. ${link('Gniew Auril','Auril i pościg')}</p></details>
  <details class="track-card"><summary>Osiem wież i Rytuał Tajemnego Oktetu</summary><p class="track-caption">Wskazówka i ukończenie wyzwania to osobne rzeczy. Osiem ukończonych wież jest sugerowanym warunkiem awansu; cały rytuał przed iglicą wykonuje każdy uczestnik. ${sectionLink('Rytuał Tajemnego Oktetu','Kolejność rytuału')}</p><div class="table-scroll"><table><thead><tr><th>Wieża</th><th>Wskazówka poznana</th><th>Wyzwanie ukończone</th></tr></thead><tbody>${T.towers.map(t=>`<tr><td>${link(t)}</td>${['clue','cleared'].map(f=>`<td><input type="checkbox" data-tower="${t}" data-field="${f}" aria-label="${t}: ${f==='clue'?'wskazówka':'wyzwanie'}" ${state.towers[t][f]?'checked':''}></td>`).join('')}</tr>`).join('')}</tbody></table></div><p>Wskazówki: ${Object.values(state.towers).filter(t=>t.clue).length}/8 · wyzwania: ${Object.values(state.towers).filter(t=>t.cleared).length}/8</p><p class="track-caption">Wskazówka Y11 jest w Y15; Y22 ma fałszywy napis, a Y26 — brakujące słowo. Samo odwiedzenie wieży nie odhacza wskazówki.</p><div class="track-actions">${state.players.map(p=>`<label class="track-check"><input type="checkbox" data-ritual="${p.id}" ${p.ritual?'checked':''}>${p.name}: rytuał wykonany</label>`).join('')}</div></details>
  <details class="track-card"><summary>Dodatkowe terminy i notatki</summary><ul class="track-caption"><li>${link('Y19m','Hebanowa Gwiazda')}: po jej zbadaniu, na koniec następnego długiego odpoczynku — Inteligencja ST 20. Zapisz poniżej, kogo dotyczy.</li><li>${link('Y19n','Wrzeciono')}: po aktywacji tłumienie magii przez 24 h w promieniu 3 mil.</li><li>Przyrząd Dwóch Brzegów: odpowiedź rozmówcy zużywa próbę na 24 h.</li><li>Auril wychodzi szukać drużyny godzinę po ultimatum; późniejsze godzinowe sprawdzenia pościgu mają 20% szans. Możesz utworzyć powtarzane przypomnienie.</li></ul><form data-form="timer" class="track-form"><label>Nazwa<input name="name" maxlength="160" placeholder="Np. koniec tłumienia magii" required></label><label>Za ile minut<input type="number" name="minutes" min="1" max="100800" value="1440" required></label><label class="track-check"><input type="checkbox" name="repeat">Powtarzaj co ten czas</label><button>Dodaj termin</button></form><ul>${state.timers.filter(t=>!t.done).map(t=>`<li>${safe(t.name)} · ${remaining(t.at)}${t.repeat?' · co '+time(t.repeat):''} ${button('timer-done','Rozlicz',`data-id="${t.id}" ${t.at<=state.time?'':'disabled'}`)}</li>`).join('')||'<li>Brak dodatkowych terminów.</li>'}</ul><form data-form="notes"><label for="tracker-notes">Notatki sesji — efekty, zapasy, straty patroli</label><textarea id="tracker-notes" name="text" rows="4" maxlength="30000">${safe(state.notes)}</textarea><button>Zapisz notatki</button></form></details>
  <details class="track-card"><summary>Historia zmian</summary><ol class="track-caption">${state.log.map(l=>`<li><strong>${time(l.at)}</strong> — ${safe(l.text)}</li>`).join('')||'<li>Brak zmian.</li>'}</ol></details></fieldset><div class="track-bottom">${button('reset','Rozpocznij nowy zapis')}<span class="track-caption">Stan liczników nie zmienia notatek kampanii.</span></div>`;
  host.querySelector('#track-explore').checked=exploring;
  host.querySelectorAll('form[data-form="exhaustion"]').forEach(form=>{
   const p=state.players[Number(form.dataset.player)];if(!p.hunger)return;
   form.insertAdjacentHTML('afterend',`<form data-form="hunger-time" data-player="${p.id}" class="track-form"><label>Ulga jeszcze (min)<input name="minutes" type="number" min="0" max="60" placeholder="Nieustalone" value="${p.hungerNext===null?'':Math.min(60,Math.max(0,p.hungerNext-state.time))}" required></label><button>Ustaw termin</button></form>`);
  });
 }
 function saveAction(a){if(locked)throw Error('Najpierw wczytaj poprawny zapis lub rozpocznij nowy.');const next=T.reduce(state,a);history.push(state);history=history.slice(-20);state=next;message=state.log[0].text;persist();refresh();}
 function refresh(){const host=document.querySelector('#tracker-panel');const open=[...host.querySelectorAll('details')].map(d=>d.open);render();host.querySelectorAll('details').forEach((d,i)=>{if(i<open.length)d.open=open[i]});}
 function error(e){message=e.message;document.querySelector('#tracker-feedback').textContent=message;}
 function setup(){
  load();const host=document.querySelector('#tracker-panel');
  host.addEventListener('click',e=>{const b=e.target.closest('button[data-track]');if(!b)return;const action=b.dataset.track,player=Number(b.dataset.player);try{
   if(action==='export'){const blob=new Blob([JSON.stringify({format:'icewind-ythryn',state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ythryn-zapis-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}
   if(action==='import'){document.querySelector('#tracker-import').click();return;}
   if(action==='reset'){if(!confirm('Rozpocząć nowy zapis od 0 h? Pobierz kopię, jeśli chcesz zachować obecny stan.'))return;history=[state];state=T.fresh();locked=false;persist();message='Rozpoczęto nowy zapis.';refresh();return;}
   if(action==='undo'){if(locked||!history.length)return;state=history.pop();persist();message='Cofnięto ostatnią zmianę.';refresh();return;}
   if(action==='advance')return saveAction({type:'time',minutes:Number(b.dataset.minutes),explore:document.querySelector('#track-explore').checked});
   if(action==='rest'||action==='rest-end')return saveAction({type:'rest',minutes:action==='rest'?480:0});
   if(action==='pass'||action==='fail')return saveAction({type:'blight',player,pass:action==='pass',die:Number(document.querySelector('#die-'+player)?.value)});
   saveAction({type:action,player,id:Number(b.dataset.id)});
  }catch(err){error(err)}});
  host.addEventListener('submit',e=>{e.preventDefault();const f=e.target,d=new FormData(f),type=f.dataset.form;try{
   if(type==='advance')saveAction({type:'time',minutes:Number(d.get('minutes')),explore:document.querySelector('#track-explore').checked});
   if(type==='player')saveAction({type:'player-edit',player:Number(f.dataset.player),status:d.get('status'),dc:Number(d.get('dc')),success:Number(d.get('success')),fail:Number(d.get('fail'))});
   if(type==='exhaustion')saveAction({type:'exhaustion',player:Number(f.dataset.player),value:Number(d.get('value'))});
   if(type==='hunger-time')saveAction({type:'hunger-time',player:Number(f.dataset.player),minutes:Number(d.get('minutes'))});
   if(type==='factions')saveAction({type:'factions',entry:d.get('entry')===''?null:Math.round(Number(d.get('entry'))*60),delay:Math.round(Number(d.get('delay'))*60),avarice:d.get('avarice'),auril:d.get('auril')});
   if(type==='timer')saveAction({type:'timer',name:d.get('name'),minutes:Number(d.get('minutes')),repeat:d.has('repeat')});
   if(type==='notes')saveAction({type:'notes',text:d.get('text')});
  }catch(err){error(err)}});
  host.addEventListener('change',async e=>{const el=e.target;try{
   if(el.dataset.tower)saveAction({type:'tower',code:el.dataset.tower,field:el.dataset.field,value:el.checked});
   if(el.dataset.ritual!==undefined)saveAction({type:'ritual',player:Number(el.dataset.ritual),value:el.checked});
   if(el.id==='tracker-import'&&el.files[0]){if(el.files[0].size>1000000)throw Error('Plik jest zbyt duży. Wybierz zapis JSON z tego licznika.');const data=JSON.parse(await el.files[0].text());if(data.format!=='icewind-ythryn')throw Error('To nie jest zapis licznika Ythryn.');const next=T.validate(data.state);if(!confirm('Zastąpić obecny stan wczytanym zapisem?'))return;history=[state];state=next;locked=false;persist();message='Wczytano zapis.';refresh();}
  }catch(err){error(err)}});
 }
 return {setup,render};
})();
