// <auto-generated />
using System;
using MasterCompanion.Engine.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MasterCompanion.Engine.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008213443_CharacterCatalog")]
    partial class CharacterCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("engine")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("FoldersRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ModuleVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<long>("SessionsRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("Campaigns", "engine");
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.CampaignCharacter", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BackstoryMaterialId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NotesMaterialId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("CampaignId", "Id");

                    b.HasIndex("BackstoryMaterialId");

                    b.HasIndex("NotesMaterialId");

                    b.ToTable("Characters", "engine");
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.CampaignFolder", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("CampaignId", "Id");

                    b.HasIndex("CampaignId", "ParentId");

                    b.ToTable("Folders", "engine");
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.CampaignGameState", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("CampaignId");

                    b.ToTable("GameStates", "engine");
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.CampaignMap", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Maps", "engine");
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.CampaignSession", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("FollowUp")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("NotesMaterialId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PinnedMaterialIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PreparationMaterialId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("CampaignId", "Id");

                    b.HasIndex("CampaignId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'active'");

                    b.HasIndex("NotesMaterialId");

                    b.HasIndex("PreparationMaterialId");

                    b.HasIndex("CampaignId", "Sequence")
                        .IsUnique();

                    b.ToTable("Sessions", "engine");
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.FolderOperationReceipt", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("CampaignId", "RequestId");

                    b.HasIndex("CampaignId", "Revision")
                        .IsUnique();

                    b.ToTable("FolderOperationReceipts", "engine");
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.GameOperation", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("BeforeJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<bool>("Undone")
                        .HasColumnType("boolean");

                    b.HasKey("CampaignId", "RequestId");

                    b.HasIndex("CampaignId", "Revision")
                        .IsUnique();

                    b.HasIndex("CampaignId", "Undone", "Revision");

                    b.ToTable("GameOperations", "engine");
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.Material", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("DocumentSchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("FolderId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "FolderId");

                    b.ToTable("Materials", "engine");
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.MaterialDeletionReceipt", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("CampaignId", "RequestId");

                    b.ToTable("MaterialDeletionReceipts", "engine");
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.SessionOperationReceipt", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("CampaignId", "RequestId");

                    b.HasIndex("CampaignId", "Revision")
                        .IsUnique();

                    b.ToTable("SessionOperationReceipts", "engine");
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.CampaignCharacter", b =>
                {
                    b.HasOne("MasterCompanion.Engine.Persistence.Material", null)
                        .WithMany()
                        .HasForeignKey("BackstoryMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MasterCompanion.Engine.Persistence.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterCompanion.Engine.Persistence.Material", null)
                        .WithMany()
                        .HasForeignKey("NotesMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.CampaignFolder", b =>
                {
                    b.HasOne("MasterCompanion.Engine.Persistence.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterCompanion.Engine.Persistence.CampaignFolder", null)
                        .WithMany()
                        .HasForeignKey("CampaignId", "ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.CampaignGameState", b =>
                {
                    b.HasOne("MasterCompanion.Engine.Persistence.Campaign", null)
                        .WithOne()
                        .HasForeignKey("MasterCompanion.Engine.Persistence.CampaignGameState", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.CampaignMap", b =>
                {
                    b.HasOne("MasterCompanion.Engine.Persistence.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.CampaignSession", b =>
                {
                    b.HasOne("MasterCompanion.Engine.Persistence.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterCompanion.Engine.Persistence.Material", null)
                        .WithMany()
                        .HasForeignKey("NotesMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MasterCompanion.Engine.Persistence.Material", null)
                        .WithMany()
                        .HasForeignKey("PreparationMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.FolderOperationReceipt", b =>
                {
                    b.HasOne("MasterCompanion.Engine.Persistence.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.GameOperation", b =>
                {
                    b.HasOne("MasterCompanion.Engine.Persistence.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.Material", b =>
                {
                    b.HasOne("MasterCompanion.Engine.Persistence.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterCompanion.Engine.Persistence.CampaignFolder", null)
                        .WithMany()
                        .HasForeignKey("CampaignId", "FolderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.MaterialDeletionReceipt", b =>
                {
                    b.HasOne("MasterCompanion.Engine.Persistence.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MasterCompanion.Engine.Persistence.SessionOperationReceipt", b =>
                {
                    b.HasOne("MasterCompanion.Engine.Persistence.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
